apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
        - name: kubernetes-calc
          image: australia-southeast2-docker.pkg.dev/sit323-25t1-copley-14a816f/calculator-repo/calculator-app:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calc
  ports:
    - port: 4026
      targetPort: 8080
  type: LoadBalancer
